### ISSUE TITLE
Windows - Zip cannot be opened by Chrome Browser or Mozilla Addons Store

### ISSUE THREAD

**Issue by ashclarke** [feross/cross-zip#11]
Hi,

I'm using cross-zip on Windows 10 and I'm experiencing an issue where it believes the file is "corrupted" in certain situations.

The zips are creating using an NPM script, so I have both cross-zip and cross-zip-cli installed:

`cross-var cross-zip build dist/$npm_package_name-$npm_package_version.production.zip`

The zip is created in the directory but I get the following issues when trying to use the zip:

* ![image](https://user-images.githubusercontent.com/963023/33551055-05505776-d8e8-11e7-8fcf-591477b76368.png)

* I also get the following error message from Chrome when trying to drag and drop the zip into the `chrome://extensions` page: "Failed to load extension from: \<path\>. Could not unzip extension for install."

There was a suggestion, in an issue on the Mozilla Addons repository, that it could relate to the behaviour of the [System.IO.Compression.ZipFile](https://github.com/mozilla/addons/issues/541#issuecomment-348542956) class.

Do you know if there is anything that can be done?

EDIT:

I attempted to put all files at the top level of the zip, but this still did not allow the zip to be loaded in Chrome

**Comment by feross** [comment]
Sorry, I'm not sure what the issue is. Do leave a comment if you figure it out.
