### ISSUE TITLE
Specify encoding on win32 platform

### ISSUE THREAD

**Issue by ZhangPuXi** [feross/cross-zip#14]
- For some reason, the default charset encoding of my system is not utf-8, and other people couldn't unzip the file generated on my computer. So I suggest specify the encoding to utf-8 explicitly.

```
function getZipCommand (inPath, outPath) {
  if (process.platform === 'win32') {
    return `powershell.exe -nologo -noprofile -command "& { Add-Type -A 'System.IO.Compression.FileSystem'; Add-Type -A 'System.Text.Encoding'; [IO.Compression.ZipFile]::CreateFromDirectory('${inPath}', '${outPath}', '${1}', '${true}', [System.Text.Encoding]::UTF8 ); }"`
  } else {
    var dirPath = path.dirname(inPath)
    var fileName = path.basename(inPath)
    return `cd ${JSON.stringify(dirPath)} && zip -r -y ${JSON.stringify(outPath)} ${JSON.stringify(fileName)}`
  }
}
```

**Comment by feross** [comment]
I tried your suggested code and the tests fail now. Due to time constraints, I don't have any plans to work on this. If you would like to see it fixed, please send a pull request!

![mickey-wizard](https://user-images.githubusercontent.com/121766/62907205-e7fc7680-bd26-11e9-83f3-9614f069b5e0.gif)
