### ISSUE TITLE
How to compress files without including their parent folder?

### ISSUE THREAD

**Issue by niklashigi** [feross/cross-zip#15]
I'm not sure if this is a bug or intended behavior, but in my app I'm using both `unzip` and `zip` to first unpack a zip file, then modify its contents, and finally zip all the files again.

Since `unzip` takes a zip file containing files `./a.txt` and `./b.txt` and puts them into the directory `./example`, I expected `zip` to take the files `./example/a.txt` and `./example/a.txt` and put them into the zip file as `./a.txt` and `./b.txt`. That's not the case, however, as the `./example` directory is included in the zip file and there's seemingly no way to put files at the root of the zip file (and recreate the original zip).

Is there a way to do this? (I'm using `cross-zip` v2.1.6 on Linux.)

**Comment by toyobayashi** [comment]
@shroudedcode I met the same issue. I have a fork and have fixed it. [@tybys/cross-zip](https://github.com/toyobayashi/cross-zip)

**Comment by niklashigi** [comment]
@toyobayashi Thanks for such a great fork! I'm now using it in [`apk-mitm`](https://github.com/shroudedcode/apk-mitm).

**Comment by feross** [comment]
@toyobayashi Can you send a PR to integrate your fixes into this package?

**Comment by toyobayashi** [comment]
@feross But this package has been almost completely rewritten in my fork, with API breaking change. Should I merge the latest code into another branch then do some fix?

**Comment by feross** [comment]
Ah, okay. If the code has changed that much then it's probably not worth it. I was just interested in getting the bug fixed with the parent folder being included.

**Comment by jespertheend** [comment]
I'm using this package on github actions, and it seems like on ubuntu the parent folder is included and on windows it isn't
