### ISSUE TITLE
cross-unzip?

### ISSUE THREAD

**Issue by fritx** [feross/cross-zip#2]
It seems that [node-unzip](https://github.com/EvanOxfeld/node-unzip) and [node-tar](https://github.com/npm/node-tar) use pure Javascript to do the job.
I worry about their efficiency.

**Comment by feross** [comment]
Hey, I literally just made a repo and was about to publish, but you beat me by one minute!

https://github.com/feross/cross-unzip

**Comment by feross** [comment]
@fritx If you want, we can use my version which has a parallel API to `cross-zip` -- i.e. it's sync, which is easier for use in build scripts, etc.

**Comment by fritx** [comment]
@feross hey, cool, it's funny LOL
Please give me more time to think about it.
But can you add that just into cross-zip? What's the pros and cons?

**Comment by feross** [comment]
No problem. I just shipped it in this package. See https://github.com/feross/cross-zip#api
