### ISSUE TITLE
unzip fails on Windows when the path contains a space

### ISSUE THREAD

**Issue by malept** [feross/cross-zip#23]
Per https://github.com/feross/cross-zip/issues/19#issuecomment-584769787, the Powershell command does not handle paths with spaces in them. Here is the error output from a run in Travis CI/Windows:

https://travis-ci.com/malept/cross-zip/jobs/286009985#L81

And the test code that causes it:

https://github.com/malept/cross-zip/blob/a349ed0f8e439fc91b1368318659f52750a5d645/test/unzip.js#L44-L65

**Comment by feross** [comment]
@malept Released as 3.1.0
