### ISSUE TITLE
Using unzip produces cb(err)

### ISSUE THREAD

**Issue by paulhocker** [feross/cross-zip#6]
Using unzip as documented produces the following message after completion. I was able to correct the error by adding a callback as a third parameter for the unzip. Is this just missing in the documentation, or is there a better way to make it work?
# Original Code

`
    var zip = require('cross-zip');
    zip.unzip('./test.zip', './tmp');
`

Produces:

C:\Users\Paul\AppData\Roaming\npm\node_modules\cross-zip\index.js:87
    cb(err)
    ^

TypeError: cb is not a function
    at C:\Users\Paul\AppData\Roaming\npm\node_modules\cross-zip\index.js:87:5
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
# Correct and Functional Code

`
    var zip = require('cross-zip');
    zip.unzip('./test.zip', './tmp', function() {
        console.log("done");
    });
`

Produces:

done

**Comment by feross** [comment]
Thanks for the issue. You're right, the docs were slightly off. The async unzip method takes a callback. Fixed now!

I suppose we can also make the `callback` optional. Will do that as well.

**Comment by feross** [comment]
2.1.2
